/*
 * main.c  –  STM32 #1  :  ECU Simulator / Transmitter
 *
 * This board pretends to be a vehicle ECU.
 * It generates fake Speed, RPM, Fuel, Temperature, Battery, and Throttle
 * data, then broadcasts them as CAN frames every 100 ms.
 *
 * ─── Pin connections (STM32F103C8T6 "Blue Pill") ────────────────────
 *
 *  MCP2515 Module      STM32
 *  ──────────────────  ─────────────────────────────
 *  VCC                 3.3 V
 *  GND                 GND
 *  SCK                 PA5  (SPI1 CLK)
 *  SI  (MOSI)          PA7  (SPI1 MOSI)
 *  SO  (MISO)          PA6  (SPI1 MISO)
 *  CS                  PA4  (GPIO output, active-LOW)
 *  INT                 PB0  (GPIO input, optional – polled not used here)
 *
 *  CAN H / CAN L of BOTH boards must be connected together via
 *  120 Ω termination resistors at each end of the bus.
 *
 * ─── Clocks ─────────────────────────────────────────────────────────
 *  SystemCoreClock = 72 MHz (HSE 8 MHz + PLL ×9)
 *  APB2 (SPI1)     = 36 MHz  → SPI prescaler /4 → 9 Mbit/s
 *  MCP2515 max SPI = 10 Mbit/s  ✓
 */

#include "main.h"
#include "mcp2515.h"
#include "ecu_simulator.h"
#include <string.h>

/* ─── Peripheral handles ────────────────────────────────────────────── */
SPI_HandleTypeDef  hspi1;
UART_HandleTypeDef huart1;   /* Debug UART – PA9 TX, PA10 RX, 115200 baud */

/* ─── Prototypes ────────────────────────────────────────────────────── */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_SPI1_Init(void);
static void MX_USART1_Init(void);
static void Debug_Print(const char *msg);

/* ─── Main ──────────────────────────────────────────────────────────── */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_SPI1_Init();
    MX_USART1_Init();

    Debug_Print("\r\n=== CAN Bus ECU Simulator ===\r\n");

    /* Initialise MCP2515 – CS on PA4 */
    if (MCP2515_Init(&hspi1, GPIOA, GPIO_PIN_4) != MCP_OK) {
        Debug_Print("[ERROR] MCP2515 init failed!\r\n");
        while (1) {
            HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);  /* Built-in LED blink */
            HAL_Delay(200);
        }
    }

    Debug_Print("[OK] MCP2515 ready at 500 kbps\r\n");
    Debug_Print("[INFO] Transmitting ECU data every 100 ms...\r\n\r\n");

    ECU_State ecu;
    memset(&ecu, 0, sizeof(ecu));

    uint32_t last_tx = 0;

    while (1)
    {
        uint32_t now = HAL_GetTick();

        /* Transmit every 100 ms */
        if (now - last_tx >= 100)
        {
            last_tx = now;

            ECU_UpdateState(&ecu, now);
            ECU_TransmitAll(&ecu);

            /* Print current state over UART for easy debugging */
            char buf[80];
            snprintf(buf, sizeof(buf),
                     "SPD:%3u RPM:%4u FUEL:%3u%% TEMP:%3u BAT:%5u THR:%3u%%\r\n",
                     ecu.speed_kmh, ecu.rpm, ecu.fuel_pct,
                     ecu.coolant_temp_c, ecu.battery_mv, ecu.throttle_pct);
            Debug_Print(buf);

            /* Heartbeat LED */
            HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        }
    }
}

/* ─── Debug UART helper ─────────────────────────────────────────────── */
static void Debug_Print(const char *msg)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)msg, strlen(msg), HAL_MAX_DELAY);
}

/* ─── Peripheral init (generated by STM32CubeMX, included inline) ──── */

static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef osc = {0};
    RCC_ClkInitTypeDef clk = {0};

    osc.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState       = RCC_HSE_ON;
    osc.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
    osc.PLL.PLLState   = RCC_PLL_ON;
    osc.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLMUL     = RCC_PLL_MUL9;   /* 8 MHz × 9 = 72 MHz */
    HAL_RCC_OscConfig(&osc);

    clk.ClockType      = RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK |
                         RCC_CLOCKTYPE_PCLK1  | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV2;   /* 36 MHz */
    clk.APB2CLKDivider = RCC_HCLK_DIV1;   /* 72 MHz */
    HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_2);
}

static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef gpio = {0};

    /* Enable clocks */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* PC13 – built-in LED (active low) */
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);
    gpio.Pin   = GPIO_PIN_13;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &gpio);

    /* PA4 – MCP2515 CS (output, start HIGH = deselected) */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
    gpio.Pin   = GPIO_PIN_4;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOA, &gpio);
}

static void MX_SPI1_Init(void)
{
    __HAL_RCC_SPI1_CLK_ENABLE();

    hspi1.Instance               = SPI1;
    hspi1.Init.Mode              = SPI_MODE_MASTER;
    hspi1.Init.Direction         = SPI_DIRECTION_2LINES;
    hspi1.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi1.Init.CLKPolarity       = SPI_POLARITY_LOW;   /* CPOL=0 */
    hspi1.Init.CLKPhase          = SPI_PHASE_1EDGE;    /* CPHA=0 */
    hspi1.Init.NSS               = SPI_NSS_SOFT;
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8; /* 72/8 = 9 Mbit/s */
    hspi1.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    hspi1.Init.TIMode            = SPI_TIMODE_DISABLE;
    hspi1.Init.CRCCalculation    = SPI_CRCCALCULATION_DISABLE;
    HAL_SPI_Init(&hspi1);

    /* SPI GPIO: PA5=SCK, PA6=MISO, PA7=MOSI */
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin   = GPIO_PIN_5 | GPIO_PIN_7;
    gpio.Mode  = GPIO_MODE_AF_PP;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOA, &gpio);

    gpio.Pin  = GPIO_PIN_6;
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &gpio);
}

static void MX_USART1_Init(void)
{
    __HAL_RCC_USART1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PA9 TX, PA10 RX */
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin   = GPIO_PIN_9;
    gpio.Mode  = GPIO_MODE_AF_PP;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOA, &gpio);

    gpio.Pin  = GPIO_PIN_10;
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &gpio);

    huart1.Instance          = USART1;
    huart1.Init.BaudRate     = 115200;
    huart1.Init.WordLength   = UART_WORDLENGTH_8B;
    huart1.Init.StopBits     = UART_STOPBITS_1;
    huart1.Init.Parity       = UART_PARITY_NONE;
    huart1.Init.Mode         = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart1);
}

/* ─── HAL weak callbacks ────────────────────────────────────────────── */
void Error_Handler(void)
{
    while (1) {
        HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        HAL_Delay(100);
    }
}
